version: 2

updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      include: "scope"
      prefix: "composer"
    labels:
      - "enhancement"
    versioning-strategy: "widen"
